### PR TITLE
Added some fixes for PHP 8.2 and other smaller cleanup.

### PR DESCRIPTION
**Pull request by hostep**
Hi there

Added some fixes:
- wrong use of global `Exception` (`Magento\Setup\Exception` doesn't exists)
- returning response/result in controller according to phpdoc
- adding missing `$aggregation` & `$logger` members (fixes PHP 8.2 deprecated usage of [creation of dynamic properties](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties))
- returning `$this` in DataPatches, according to phpdoc
- fixed php version constraints in `composer.json` (if you specify `~8.1`, it will match 8.1 till 8.9999, if you however specify `~8.1.0` it will only match 8.1.0 to 8.1.999, which is what you want here, [see documentation](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-))

All these (except the `composer.json` one) were found by using the [phpstan tool](https://github.com/phpstan/phpstan) and scanning on level 0, these are the things it reported and are now fixed (it finds more problems, but those are more complicated to solve and since I don't know this module very well, I decided not to try to tackle those left overs):

```
$ /path/to/phpstan analyse --level=0 .

 ------ --------------------------------------------------------------------------------------------------------
  Line   Controller/Adminhtml/AutoConnect/AutoGenerateApiUser.php
 ------ --------------------------------------------------------------------------------------------------------
  98     Instantiated class Magento\Setup\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  145    Instantiated class Magento\Setup\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  189    Instantiated class Magento\Setup\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Controller/Adminhtml/Configuration/Save.php
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  42     Method SendCloud\SendCloud\Controller\Adminhtml\Configuration\Save::execute() should return Magento\Framework\App\ResponseInterface|Magento\Framework\Controller\ResultInterface but return statement is missing.
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  ------ ---------------------------------------------------------------------
  Line   Model/CheckoutConfiguration.php
 ------ ---------------------------------------------------------------------
  106    Caught class SendCloud\SendCloud\Model\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  145    Caught class SendCloud\SendCloud\Model\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  174    Caught class SendCloud\SendCloud\Model\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ---------------------------------------------------------------------

  ------ ----------------------------------------------------------------------------------------------------------------------------
  Line   Model/ResourceModel/SendcloudDeliveryMethod/Collection.php
 ------ ----------------------------------------------------------------------------------------------------------------------------
  48     Access to an undefined property SendCloud\SendCloud\Model\ResourceModel\SendcloudDeliveryMethod\Collection::$aggregations.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
  59     Access to an undefined property SendCloud\SendCloud\Model\ResourceModel\SendcloudDeliveryMethod\Collection::$aggregations.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
 ------ ----------------------------------------------------------------------------------------------------------------------------

  ------ --------------------------------------------------------------------------------------------------------------------------
  Line   Model/ResourceModel/SendcloudDeliveryZone/Collection.php
 ------ --------------------------------------------------------------------------------------------------------------------------
  39     Access to an undefined property SendCloud\SendCloud\Model\ResourceModel\SendcloudDeliveryZone\Collection::$aggregations.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
  50     Access to an undefined property SendCloud\SendCloud\Model\ResourceModel\SendcloudDeliveryZone\Collection::$aggregations.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
 ------ --------------------------------------------------------------------------------------------------------------------------

  ------ ----------------------------------------------------------------------------------------------------
  Line   Plugin/Order/CheckoutOrderRepository.php
 ------ ----------------------------------------------------------------------------------------------------
  74     Access to an undefined property SendCloud\SendCloud\Plugin\Order\CheckoutOrderRepository::$logger.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
 ------ ----------------------------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------------------------------
  Line   Plugin/Order/OrderRepository.php
 ------ --------------------------------------------------------------------------------------------
  81     Access to an undefined property SendCloud\SendCloud\Plugin\Order\OrderRepository::$logger.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
 ------ --------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Setup/Patch/Data/UpdateInternationalShipping.php
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  101    Method SendCloud\SendCloud\Setup\Patch\Data\UpdateInternationalShipping::apply() should return $this(SendCloud\SendCloud\Setup\Patch\Data\UpdateInternationalShipping) but return statement is missing.
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Setup/Patch/Data/UpdateServicePoint.php
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  105    Method SendCloud\SendCloud\Setup\Patch\Data\UpdateServicePoint::apply() should return $this(SendCloud\SendCloud\Setup\Patch\Data\UpdateServicePoint) but return statement is missing.
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Be sure to double check all changes, I haven't tested anything, only looked at the output of phpstan.

Thanks!

### CODE REVIEW

**Comment by hostep** [comment]
Added an additional change: dropping support for PHP 7.0 from the `composer.json` constraints, since you guys use nullable types syntax here and there which was only [introduced in PHP 7.1](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types)

Examples:
```
$ find . -type f ! -path '*/vendor/*' -iname '*.php' -exec php70 -l {} \;

PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Block/Adminhtml/AbstractOrder.php on line 33

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Block/Adminhtml/AbstractOrder.php on line 33

Errors parsing ./Block/Adminhtml/AbstractOrder.php
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Block/Adminhtml/Form.php on line 34

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Block/Adminhtml/Form.php on line 34

Errors parsing ./Block/Adminhtml/Form.php
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Helper/Checkout.php on line 51

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in ./Helper/Checkout.php on line 51

Errors parsing ./Helper/Checkout.php
```

**Comment by tanjalog** [comment]
Dear @hostep 

Thanks for reaching out to us.

We will investigate your request and get back to you as soon as possible.

Best regards

**Comment by logeecom** [comment]
[to client on git]

Hi @hostep 

Thank you for your request, please note that we review it and accepted and regarding this, a new version of the plugin is released on the marketplace.

Best regards

**Comment by hostep** [comment]
Thanks @logeecom!

Can you please make sure the github repo is up2date with the latest version? It's easier to review the changes between versions this way.

**Pull request closed without merging**
